source: src
paths:
  uploads: uploads
_enabled_editors:
  - data
data_config: {}
timezone: US/Central
collections_config:
  songs:
    name: Song
    path: _data/songs
    output: false
    icon: music_note
    _enabled_editors:
      - data
    schemas:
      default:
        path: _includes/schemas/song.md
