paths:
  uploads: uploads
  static: ''
  collections: ''
  data: _data
  layouts: _includes
  includes: _includes
collections_config: {}
_enabled_editors:
  - data
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: US/Central
collections_config:
  songs:
    path: _data/songs/
    icon: music_note
    _enabled_editors:
      - data
    schemas:
      default:
        path: _schemas/song.md
