source: src
collections_config:
  songs:
    path: songs
    output: false
    filter:
      exclude:
        - songs.11tydata.js
    description: Songs
    icon: music_note
    _enabled_editors:
      - data
    disable_add_folder: true
    preview:
      gallery:
        text: " "
    schemas:
      default:
        path: _includes/schemas/song.html
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: music_note
collections_config_override: true
_enabled_editors:
  - data
_inputs:
  en:
    type: object
    options:
      preview:
        text: English
  es:
    type: object
    options:
      preview:
        text: Spanish
  lyrics:
    type: code
  lastfm:
    type: url
  spotify:
    type: url
  tidal:
    type: url
  youtube:
    type: url
  layout:
    type: auto
    hidden: true
    cascade: true
  eleventyExcludeFromCollections:
    type: auto
    hidden: true
    cascade: true
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: US/Central
