source: src
paths:
  uploads: uploads
collections_config:
  songs:
    path: songs
    output: false
    name: Song
    description: ''
    icon: music_note
    _editables: {}
    _enabled_editors:
      - data
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: _includes/schemas/song.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
collections_config_override: true
_enabled_editors:
  - data
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: US/Central
