source: src
paths:
  uploads: uploads
collections_config:
  songs:
    path: songs
    description: Songs
    output: false
    schemas:
      default:
        path: _includes/schemas/song.html
    disable_add_folder: true
    _enabled_editors:
      - data
    filter:
      exclude:
        - songs.11tydata.js
_enabled_editors:
  - data
_inputs:
  layout:
    hidden: true
  eleventyExcludeFromCollections:
    hidden: true
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: US/Central
