source: src
paths:
  uploads: uploads
collections_config:
  songs:
    path: songs
    output: false
    filter:
      exclude:
        - songs.11tydata.js
    description: Songs
    icon: notes
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    # preview:
    #   gallery:
    #     image:
    #       - key: urls.spotify
    schemas:
      default:
        path: _includes/schemas/song.html
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
collections_config_override: true
collection_groups:
  - heading: Taylor’s Songs
    collections:
      - songs
_enabled_editors:
  - data
_inputs:
  en:
    type: object
    options:
      preview:
        text: English
  es:
    type: object
    options:
      preview:
        text: Spanish
  lyrics:
    type: markdown
  # External streaming urls
  lastfm:
    type: url
  spotify:
    type: url
  tidal:
    type: url
  youtube:
    type: url
  layout:
    type: auto
    hidden: true
    cascade: true
  eleventyExcludeFromCollections:
    type: auto
    hidden: true
    cascade: true
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: US/Central
